// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig } from "prisma/config";

const currentDir = dirname(fileURLToPath(import.meta.url));

// Always resolve env files from the platform project directory, regardless of cwd.
loadEnv({ path: resolve(currentDir, ".env") });
loadEnv({ path: resolve(currentDir, ".env.local"), override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    //seed: `tsx prisma/seed.ts`,
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});